//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *GlobalGatewayPolicy) DeepCopyInto(out *GlobalGatewayPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	if in.Spec.RegionalEndpointOverrides != nil {
		out.Spec.RegionalEndpointOverrides = append([]RegionalEndpointOverride(nil), in.Spec.RegionalEndpointOverrides...)
	}
}

func (in *GlobalGatewayPolicy) DeepCopy() *GlobalGatewayPolicy {
	if in == nil {
		return nil
	}
	out := new(GlobalGatewayPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *GlobalGatewayPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *GlobalGatewayPolicyList) DeepCopyInto(out *GlobalGatewayPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GlobalGatewayPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *GlobalGatewayPolicyList) DeepCopy() *GlobalGatewayPolicyList {
	if in == nil {
		return nil
	}
	out := new(GlobalGatewayPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *GlobalGatewayPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *GlobalGatewayPolicyStatus) DeepCopyInto(out *GlobalGatewayPolicyStatus) {
	*out = *in
	if in.Members != nil {
		out.Members = make([]MemberStatus, len(in.Members))
		for i := range in.Members {
			out.Members[i] = in.Members[i]
			if in.Members[i].Conditions != nil {
				out.Members[i].Conditions = append([]metav1.Condition(nil), in.Members[i].Conditions...)
			}
		}
	}
	if in.Conditions != nil {
		out.Conditions = append([]metav1.Condition(nil), in.Conditions...)
	}
}
